---
# yamllint disable rule:line-length rule:truthy
name: Build add-on

env:
  BUILD_ARGS: "--test"

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build amd64 tellstick add-on

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.0

      - name: Set build arguments
        run: |
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
          fi

      - name: Login to DockerHub
        if: env.BUILD_ARGS == '--docker-hub-check'
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build tellstick add-on
        uses: home-assistant/builder@2025.11.0
        with:
          image: amd64
          args: |
            ${{ env.BUILD_ARGS }} \
            --amd64 \
            --target /data/tellstick \
            --addon
